{% set name = "geoai-py" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geoai-py-{{ version }}.tar.gz
  sha256: cc4c2a0b6fe53496d6f5faeb18de73298acb0b53f904351b28c94486b8be6e3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - segment-geospatial

test:
  imports:
    - geoai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opengeos/geoai
  summary: A Python package for using Artificial Intelligence (AI) with geospatial data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
