{% set name = "geoai-py" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geoai-py-{{ version }}.tar.gz
  sha256: cc4c2a0b6fe53496d6f5faeb18de73298acb0b53f904351b28c94486b8be6e3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - segment-geospatial

test:
  imports:
    - geoai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

outputs:
  - name: geoai-py
  - name: geoai
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("geoai-py", exact=True) }}

    test:
      requires:
        - python {{ python_min }}
      imports:
        - geoai


about:
  home: https://github.com/opengeos/geoai
  summary: A Python package for using Artificial Intelligence (AI) with geospatial data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
