{% set name = "geoai-py" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geoai_py-{{ version }}.tar.gz
  sha256: e322359084dbb9b7dc8bd7b70bb3ca6ec91b99cb972b89f9a5fbd41a903744ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - albumentations
    - contextily
    - geopandas
    - huggingface_hub
    - jupyter-server-proxy
    - leafmap
    - localtileserver
    - mapclassify
    - overturemaps
    - planetary-computer
    - pystac-client
    - rasterio
    - rioxarray
    - scikit-image
    - scikit-learn
    - segment-geospatial
    - pytorch
    - torchgeo
    - tqdm
    - transformers

test:
  imports:
    - geoai
  commands:
    - pip check
  requires:
    - pip
    - libopencv *=headless*  # [linux]
    - python {{ python_min }}

outputs:
  - name: geoai-py
  - name: geoai
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("geoai-py", exact=True) }}

    test:
      requires:
        - python {{ python_min }}
      imports:
        - geoai


about:
  home: https://github.com/opengeos/geoai
  summary: A Python package for integrating Artificial Intelligence with geospatial data analysis and visualization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
