{% set name = "geoai-py" %}
{% set version = "0.18.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geoai_py-{{ version }}.tar.gz
  sha256: d448855b3db2fd10d05c3674c1b6f32240b2be16ab3da94a924eef5434b965a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - albumentations
    - buildingregulariser
    - contextily
    - geopandas
    - huggingface_hub >=0.15.1,<1.0
    - jupyter-server-proxy
    - leafmap
    - localtileserver
    - mapclassify
    - maplibre >=0.3.0
    - opencv
    - overturemaps
    - planetary-computer
    - pystac-client
    - rasterio
    - rioxarray
    - scikit-image
    - scikit-learn
    # - segment-geospatial
    - pytorch
    - torchange
    - torchgeo
    - torchinfo
    - tqdm
    - transformers
    - packaging <25.0

test:
  imports:
    - geoai
  commands:
    - pip check
  requires:
    - pip
    - libopencv * =*headless*  # [linux]
    - python {{ python_min }}

outputs:
  - name: geoai-py
  - name: geoai
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("geoai-py", exact=True) }}

    test:
      requires:
        - python {{ python_min }}
      imports:
        - geoai


about:
  home: https://github.com/opengeos/geoai
  summary: A Python package for integrating Artificial Intelligence with geospatial data analysis and visualization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
